### ISSUE TITLE
Error with RedisCache

### ISSUE THREAD

**Issue by lexo13** [terah/fluent-pdo-model#2]
When no redis service work, error appear

`$connection = new MysqlPdo('mysql:dbname='.DB_NAME.';host='.DB_HOST.'', DB_USER, DB_PASS, $this->options, new stdOutLogger());`

error
`Catchable fatal error: Argument 1 passed to Terah\FluentPdoModel\Drivers\AbstractPdo::setCache() must be an instance of Terah\RedisCache\RedisCache, null given`

I must remove all calls to `RedisCache $cache`

**Comment by terah** [comment]
Hi,

Thanks for the bug report.  I've add a NullCache which basically does nothing removing the errors you were experiencing.  

Terry
